"""Homeowner-module mock data (dev fixtures).

Mirrors frontend/lib/homeowner/mocks/fixtures.ts. Delete once services
read from PostgreSQL.
"""

from app.shared.mock_users import days_ago, hours_ago
from app.shared.schemas.notification import ActivityOut
from app.homeowner.schemas.document import DocumentOut
from app.homeowner.schemas.project import ProjectOut
from app.homeowner.schemas.product import RecommendedProductOut
from app.homeowner.schemas.provider import RecommendedProviderOut
from app.homeowner.schemas.quote import QuoteOut
from app.homeowner.schemas.service_record import ServiceRecordOut

_hours_ago = hours_ago
_days_ago = days_ago

MOCK_PROJECTS: list[ProjectOut] = [
    ProjectOut(
        id="p-001",
        title="Kitchen Renovation",
        category="kitchen-remodeling",
        description="Full kitchen remodel: new cabinets, quartz countertops, island, and lighting.",
        status="in_progress",
        budget_min=25000,
        budget_max=40000,
        location="Austin, TX",
        progress=45,
        quotes_count=4,
        unread_messages=2,
        cover_image_url=None,
        created_at=_days_ago(21),
        updated_at=_hours_ago(5),
    ),
    ProjectOut(
        id="p-002",
        title="Roof Replacement",
        category="roofing",
        description="Replace asphalt shingle roof (~2,400 sq ft), including underlayment inspection.",
        status="quoted",
        budget_min=12000,
        budget_max=18000,
        location="Austin, TX",
        progress=0,
        quotes_count=3,
        unread_messages=1,
        cover_image_url=None,
        created_at=_days_ago(8),
        updated_at=_hours_ago(26),
    ),
    ProjectOut(
        id="p-003",
        title="Backyard Landscaping",
        category="landscaping",
        description="New patio pavers, native plant beds, and drip irrigation for a 0.2-acre backyard.",
        status="matching",
        budget_min=8000,
        budget_max=12000,
        location="Austin, TX",
        progress=0,
        quotes_count=0,
        unread_messages=0,
        cover_image_url=None,
        created_at=_days_ago(2),
        updated_at=_days_ago(1),
    ),
]

MOCK_QUOTES: list[QuoteOut] = [
    QuoteOut(
        id="q-101",
        project_id="p-002",
        project_title="Roof Replacement",
        provider_id="sp-01",
        provider_name="Hill Country Roofing Co.",
        provider_avatar_url=None,
        provider_verified=True,
        amount=14200,
        timeline="1–2 weeks",
        status="received",
        submitted_at=_hours_ago(6),
    ),
    QuoteOut(
        id="q-102",
        project_id="p-002",
        project_title="Roof Replacement",
        provider_id="sp-02",
        provider_name="Lone Star Exteriors",
        provider_avatar_url=None,
        provider_verified=True,
        amount=15800,
        timeline="2 weeks",
        status="received",
        submitted_at=_hours_ago(22),
    ),
    QuoteOut(
        id="q-103",
        project_id="p-001",
        project_title="Kitchen Renovation",
        provider_id="sp-03",
        provider_name="Craftline Builders",
        provider_avatar_url=None,
        provider_verified=False,
        amount=31500,
        timeline="6–8 weeks",
        status="accepted",
        submitted_at=_days_ago(14),
    ),
    QuoteOut(
        id="q-104",
        project_id="p-002",
        project_title="Roof Replacement",
        provider_id="sp-04",
        provider_name="Apex Roof & Gutter",
        provider_avatar_url=None,
        provider_verified=True,
        amount=13650,
        timeline="1 week",
        status="pending",
        submitted_at=_hours_ago(2),
    ),
]

MOCK_RECOMMENDED_PROVIDERS: list[RecommendedProviderOut] = [
    RecommendedProviderOut(
        id="sp-05",
        business_name="Verde Outdoor Design",
        avatar_url=None,
        categories=["landscaping"],
        location="Austin, TX",
        rating=4.9,
        reviews_count=132,
        verified=True,
        trust_score=96,
        response_time="~1 hr",
        match_score=94,
        match_reason="Completed 40+ patio and irrigation projects near 78704",
    ),
    RecommendedProviderOut(
        id="sp-06",
        business_name="Bluebonnet Landscapes",
        avatar_url=None,
        categories=["landscaping"],
        location="Round Rock, TX",
        rating=4.7,
        reviews_count=87,
        verified=True,
        trust_score=91,
        response_time="~3 hrs",
        match_score=88,
        match_reason="Strong match on budget range and native planting expertise",
    ),
    RecommendedProviderOut(
        id="sp-07",
        business_name="Austin Stoneworks",
        avatar_url=None,
        categories=["landscaping", "general-contracting"],
        location="Austin, TX",
        rating=4.6,
        reviews_count=54,
        verified=False,
        trust_score=84,
        response_time="~5 hrs",
        match_score=81,
        match_reason="Specializes in paver patios within your budget",
    ),
]

MOCK_RECOMMENDED_PRODUCTS: list[RecommendedProductOut] = [
    RecommendedProductOut(
        id="prod-rec-01",
        brand_id="brand-01",
        brand_name="Carrier Home Comfort",
        name="Infinity 30\" Convection Wall Oven",
        category="wall-ovens",
        price=2199,
        image_url=None,
        match_score=92,
        match_reason="Fits the Kitchen Renovation cutout and matches your energy-efficient picks",
    ),
    RecommendedProductOut(
        id="prod-rec-02",
        brand_id="brand-02",
        brand_name="Bosch Home Appliances",
        name="800 Series Induction Cooktop",
        category="cooktops",
        price=1849,
        image_url=None,
        match_score=90,
        match_reason="Induction pairs well with your quartz countertop selection",
    ),
    RecommendedProductOut(
        id="prod-rec-03",
        brand_id="brand-03",
        brand_name="Zephyr Ventilation",
        name="Anzio 36\" Under-Cabinet Range Hood",
        category="range-hoods",
        price=749,
        image_url=None,
        match_score=88,
        match_reason="Sized for a 36\" cooktop with 600 CFM ducted venting",
    ),
    RecommendedProductOut(
        id="prod-rec-04",
        brand_id="brand-04",
        brand_name="Broan-NuTone",
        name="AER Series Bath Fan & Blower",
        category="fans-and-blowers",
        price=189,
        image_url=None,
        match_score=85,
        match_reason="Quiet 1.5-sone operation for the primary bath refresh on your list",
    ),
    RecommendedProductOut(
        id="prod-rec-05",
        brand_id="brand-05",
        brand_name="LG Electronics",
        name="InstaView 27 cu ft French Door Fridge",
        category="fridges",
        price=2649,
        image_url=None,
        match_score=87,
        match_reason="Depth matches the existing fridge alcove; ENERGY STAR certified",
    ),
    RecommendedProductOut(
        id="prod-rec-06",
        brand_id="brand-06",
        brand_name="Samsung Home",
        name="Bespoke Over-the-Range Microwave",
        category="microwaves",
        price=549,
        image_url=None,
        match_score=82,
        match_reason="Panel-ready front lets you match your new cabinet finish",
    ),
]

MOCK_ACTIVITY: list[ActivityOut] = [
    ActivityOut(id="a-01", kind="quote_received", text="Apex Roof & Gutter submitted a quote", created_at=_hours_ago(2)),
    ActivityOut(id="a-02", kind="message", text="Craftline Builders replied in Kitchen Renovation", created_at=_hours_ago(4)),
    ActivityOut(id="a-03", kind="milestone_completed", text="Cabinet installation marked complete", created_at=_hours_ago(9)),
    ActivityOut(id="a-04", kind="provider_matched", text="3 providers matched to Backyard Landscaping", created_at=_days_ago(1)),
    ActivityOut(id="a-05", kind="project_created", text="You posted Backyard Landscaping", created_at=_days_ago(2)),
]

# --- Home Digital Twin -----------------------------------------------------
# One list, four categories — mirrors the `docs` table's single-table-plus-
# metadata design (see backend/db/schema.sql).

MOCK_DOCUMENTS: list[DocumentOut] = [
    DocumentOut(
        id="doc-001",
        category="invoice",
        title="Samsung French Door Refrigerator",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(210),
        tags=["kitchen", "appliance"],
        linked_appliance="Refrigerator",
        vendor="Amazon.com",
        amount=2149,
        purchase_date=_days_ago(210),
        order_number="112-4471963-2210649",
    ),
    DocumentOut(
        id="doc-002",
        category="invoice",
        title="Roof Replacement — Final Invoice",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(60),
        tags=["roof", "exterior"],
        linked_appliance=None,
        vendor="Hill Country Roofing Co.",
        amount=14200,
        purchase_date=_days_ago(60),
        order_number=None,
    ),
    DocumentOut(
        id="doc-003",
        category="warranty",
        title="Refrigerator — Manufacturer Warranty",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(210),
        tags=["kitchen", "appliance"],
        linked_appliance="Refrigerator",
        brand="Samsung",
        purchase_date=_days_ago(210),
        expires_at=_days_ago(-155),
    ),
    DocumentOut(
        id="doc-004",
        category="warranty",
        title="Roof — Workmanship Warranty",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(60),
        tags=["roof", "exterior"],
        linked_appliance=None,
        brand="Hill Country Roofing Co.",
        purchase_date=_days_ago(60),
        expires_at=_days_ago(-3615),
    ),
    DocumentOut(
        id="doc-005",
        category="warranty",
        title="HVAC System — Parts Warranty",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(320),
        tags=["hvac"],
        linked_appliance="HVAC System",
        brand="Carrier",
        purchase_date=_days_ago(320),
        expires_at=_days_ago(-10),
    ),
    DocumentOut(
        id="doc-006",
        category="photo",
        title="Kitchen — Before Renovation",
        file_url=None,
        file_type="jpg",
        uploaded_at=_days_ago(21),
        tags=["kitchen", "before"],
        linked_appliance=None,
    ),
    DocumentOut(
        id="doc-007",
        category="photo",
        title="Roof — Post-Install Inspection",
        file_url=None,
        file_type="jpg",
        uploaded_at=_days_ago(58),
        tags=["roof", "after"],
        linked_appliance=None,
    ),
    DocumentOut(
        id="doc-008",
        category="manual",
        title="Refrigerator — Owner's Manual",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(210),
        tags=["kitchen", "appliance"],
        linked_appliance="Refrigerator",
        brand="Samsung",
    ),
    DocumentOut(
        id="doc-009",
        category="manual",
        title="HVAC System — Installation & Service Guide",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(320),
        tags=["hvac"],
        linked_appliance="HVAC System",
        brand="Carrier",
    ),
]

MOCK_SERVICE_RECORDS: list[ServiceRecordOut] = [
    ServiceRecordOut(
        id="sr-001",
        service_date=_days_ago(60),
        contractor_name="Hill Country Roofing Co.",
        work_performed="Full roof replacement — asphalt shingle, ~2,400 sq ft, underlayment inspected and replaced.",
        cost=14200,
        linked_document_id="doc-002",
    ),
    ServiceRecordOut(
        id="sr-002",
        service_date=_days_ago(150),
        contractor_name="Austin HVAC Pros",
        work_performed="Annual HVAC tune-up: filter replacement, coolant level check, thermostat calibration.",
        cost=185,
        linked_document_id=None,
    ),
    ServiceRecordOut(
        id="sr-003",
        service_date=_days_ago(210),
        contractor_name=None,
        work_performed="New refrigerator delivered and installed (self-install).",
        cost=2149,
        linked_document_id="doc-001",
    ),
]
