services:
  - type: web
    runtime: python
    name: bestbuild-api
    plan: free
    rootDir: backend
    buildCommand: pip install uv && uv sync --frozen
    startCommand: uv run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: AWS_REGION
        value: us-east-1
      - key: CORS_ORIGINS
        value: https://bestbuild.ai, https://www.bestbuild.ai, https://bestbuild-api.onrender.com,http://localhost:3000
      - key: DATABASE_URL
        sync: false
      - key: COGNITO_USER_POOL_ID
        sync: false
      - key: COGNITO_APP_CLIENT_ID
        sync: false
      - key: COGNITO_APP_CLIENT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
