"""initial schema

Revision ID: 29ef3dab130e
Revises: 
Create Date: 2026-08-16 14:30:04.975117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '29ef3dab130e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'support_admin', 'moderator', name='admin_role'), server_default='moderator', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('code_alpha3', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_code', sa.String(length=10), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_name', sa.String(length=50), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code_alpha3')
    )
    op.create_table('metric_hourly_rollups',
    sa.Column('rollup_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_key', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('page_view', 'ui_click', 'api_call', 'feature_usage', name='event_category'), nullable=False),
    sa.Column('device', sa.Enum('web', 'mobile', 'api', name='event_device'), nullable=False),
    sa.Column('total_hits', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('error_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('p95_response_time_ms', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('rollup_time', 'event_key', 'device')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('subscription_name', sa.String(length=100), nullable=False),
    sa.Column('subscription_amount', sa.BigInteger(), nullable=False),
    sa.Column('subscription_period', sa.Interval(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('subscription_name')
    )
    op.create_table('admin_audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('public_announcements',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('cta_link', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('display_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_end IS NULL OR display_end > display_start', name='chk_display_time'),
    sa.ForeignKeyConstraint(['created_by'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_country', sa.String(length=100), nullable=False),
    sa.Column('user_addr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_type', sa.Enum('homeowner', 'service_provider', 'brand', name='user_type'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_country'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('company',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('docs',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doc_name', sa.String(length=150), nullable=False),
    sa.Column('doc_type', sa.Enum('verification', 'warranty', 'receipt', 'legal', 'ai_use', 'invoice', 'photo', 'manual', 'license', 'insurance', 'contract', 'spec_sheet', 'marketing', 'install_guide', name='doc_type'), nullable=False),
    sa.Column('doc_url', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=20), server_default='pdf', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('quote_received', 'message', 'match_found', 'project_update', 'system', name='notification_kind'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_status', sa.Enum('ordered', 'in_transit', 'cancelled', 'dispatched', 'completed', name='order_status'), server_default='ordered', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('quote_price', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'matching', 'quoted', 'in_progress', 'delayed', 'completed', 'cancelled', name='project_status'), server_default='pending', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget_min', sa.BigInteger(), nullable=True),
    sa.Column('budget_max', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('progress', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelling_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('delay_reason', sa.String(length=500), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_period', sa.Interval(), nullable=True),
    sa.CheckConstraint("(status = 'cancelled' AND cancelling_reason IS NOT NULL AND cancelled_by IS NOT NULL) OR (status != 'cancelled')", name='chk_cancellation'),
    sa.CheckConstraint("(status = 'delayed' AND delay_reason IS NOT NULL) OR (status != 'delayed')", name='chk_delay'),
    sa.CheckConstraint("status NOT IN ('in_progress', 'delayed', 'completed') OR (assigned_to_user_id IS NOT NULL AND quote_price IS NOT NULL AND time_period IS NOT NULL)", name='chk_assignment'),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name='chk_progress_range'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('rated_by', sa.UUID(), nullable=False),
    sa.Column('rated_for', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('rating_text', sa.String(length=200), nullable=True),
    sa.Column('rating_attachments', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('rated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cardinality(rating_attachments) <= 2', name='max_two_images'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='chk_rating_range'),
    sa.ForeignKeyConstraint(['rated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['rated_for'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('service_providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('contractor_type', sa.Enum('individual', 'organization', name='contractor_type'), nullable=False),
    sa.Column('avg_ratings', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('business_name')
    )
    op.create_table('telemetry_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('page_view', 'ui_click', 'api_call', 'feature_usage', name='event_category'), nullable=False),
    sa.Column('device', sa.Enum('web', 'mobile', 'api', name='event_device'), server_default='web', nullable=False),
    sa.Column('event_key', sa.String(length=150), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('starting_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('charged_amount', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ai_conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('brand_dealers',
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('linked_contractor_name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dealer_id')
    )
    op.create_table('brand_projects',
    sa.Column('brand_project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('linked_products', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('linked_contractor_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('brand_project_id')
    )
    op.create_table('brand_support_tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=150), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='ticket_status'), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('chat_rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('company_products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('other_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('crm_leads',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('estimated_value', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'converted', 'lost', name='crm_lead_status'), server_default='new', nullable=False),
    sa.Column('match_score', sa.SmallInteger(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('doc_embeddings',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('project_contractor_matches',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('matching_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'contractor_id')
    )
    op.create_table('project_payments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('paid_to', sa.UUID(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_through', sa.Enum('cash', 'online', name='payment_method'), nullable=False),
    sa.Column('payment_receipts', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['paid_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_quotes',
    sa.Column('project_quote_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('timeline', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'received', 'accepted', 'declined', 'expired', name='project_quote_status'), server_default='received', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_quote_id')
    )
    op.create_table('project_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('provider_past_projects',
    sa.Column('past_project_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('past_project_id')
    )
    op.create_table('service_providers_categories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('service_records',
    sa.Column('service_record_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contractor_name', sa.String(length=150), nullable=True),
    sa.Column('work_performed', sa.Text(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=True),
    sa.Column('linked_doc_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_doc_id'], ['docs.doc_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_record_id')
    )
    op.create_table('ai_conversation_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='agent_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_thought', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('chat_participants',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_table('crm_quotes',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'declined', 'expired', name='crm_quote_status'), server_default='draft', nullable=False),
    sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.lead_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_table('messages',
    sa.Column('msg_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(), server_default='conversation', nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('product_embeddings',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['company_products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('project_product_matches',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('matching_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['company_products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'product_id')
    )
    op.create_table('ai_agent_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['ai_conversation_messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('crm_invoices',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', name='crm_invoice_status'), server_default='draft', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['crm_quotes.quote_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_invoices')
    op.drop_table('ai_agent_actions')
    op.drop_table('project_product_matches')
    op.drop_table('product_embeddings')
    op.drop_table('messages')
    op.drop_table('crm_quotes')
    op.drop_table('chat_participants')
    op.drop_table('ai_conversation_messages')
    op.drop_table('service_records')
    op.drop_table('service_providers_categories')
    op.drop_table('provider_past_projects')
    op.drop_table('project_tasks')
    op.drop_table('project_quotes')
    op.drop_table('project_payments')
    op.drop_table('project_contractor_matches')
    op.drop_table('doc_embeddings')
    op.drop_table('crm_leads')
    op.drop_table('company_products')
    op.drop_table('chat_rooms')
    op.drop_table('brand_support_tickets')
    op.drop_table('brand_projects')
    op.drop_table('brand_dealers')
    op.drop_table('ai_conversations')
    op.drop_table('user_subscriptions')
    op.drop_table('telemetry_events')
    op.drop_table('service_providers')
    op.drop_table('refresh_tokens')
    op.drop_table('ratings')
    op.drop_table('projects')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_table('docs')
    op.drop_table('company')
    op.drop_table('users')
    op.drop_table('public_announcements')
    op.drop_table('admin_audit_logs')
    op.drop_table('subscriptions')
    op.drop_table('metric_hourly_rollups')
    op.drop_table('countries')
    op.drop_table('categories')
    op.drop_table('admins')
    # ### end Alembic commands ###
