"""Service-provider CRM mock data (dev fixtures).

Mirrors frontend/lib/provider/mocks/fixtures.ts. Delete once services read
from PostgreSQL.
"""

from app.service_provider.schemas.crm import (
    CrmDocumentOut,
    CrmQuoteOut,
    InvoiceOut,
    LeadOut,
    QuoteLineItem,
)
from app.shared.mock_users import days_ago, hours_ago

_days_ago = days_ago
_hours_ago = hours_ago

# Leads — same match-scoring concept a real AI matching engine would produce.
MOCK_LEADS: list[LeadOut] = [
    LeadOut(
        id="lead-001",
        customer_name="Sarah Mitchell",
        customer_email="sarah.mitchell@example.com",
        project_title="Gutter Guard Installation",
        category="roofing",
        estimated_value=3200,
        source="AI Match",
        status="converted",
        match_score=96,
        match_reason="Homeowner has an active roof warranty with your company",
        created_at=_days_ago(15),
    ),
    LeadOut(
        id="lead-002",
        customer_name="Jordan Blake",
        customer_email="jordan.blake@example.com",
        project_title="New Roof Install — 1,800 sqft",
        category="roofing",
        estimated_value=11500,
        source="Website inquiry",
        status="new",
        match_score=88,
        match_reason="Budget and timeline match your typical roofing jobs",
        created_at=_days_ago(2),
    ),
    LeadOut(
        id="lead-003",
        customer_name="Priya Nair",
        customer_email="priya.nair@example.com",
        project_title="Storm Damage Roof Repair",
        category="roofing",
        estimated_value=4800,
        source="Referral",
        status="contacted",
        match_score=91,
        match_reason="Urgent repair matches your fast-response profile",
        created_at=_days_ago(5),
    ),
    LeadOut(
        id="lead-004",
        customer_name="Devon Carter",
        customer_email="devon.carter@example.com",
        project_title="Annual Roof Inspection",
        category="roofing",
        estimated_value=350,
        source="AI Match",
        status="qualified",
        match_score=79,
        match_reason="Existing customer due for scheduled maintenance",
        created_at=_days_ago(1),
    ),
    LeadOut(
        id="lead-005",
        customer_name="Elena Ruiz",
        customer_email="elena.ruiz@example.com",
        project_title="Full Re-roof — Metal Upgrade",
        category="roofing",
        estimated_value=22000,
        source="Website inquiry",
        status="lost",
        match_score=84,
        match_reason="High-value project matching premium material specialization",
        created_at=_days_ago(30),
    ),
]

MOCK_CRM_QUOTES: list[CrmQuoteOut] = [
    CrmQuoteOut(
        id="quote-001",
        lead_id="lead-001",
        customer_name="Sarah Mitchell",
        title="Gutter Guard Installation",
        line_items=[
            QuoteLineItem(description="Aluminum gutter guards — 180 linear ft", quantity=180, unit_price=18),
            QuoteLineItem(description="Installation labor", quantity=1, unit_price=600),
        ],
        amount=3840,
        status="accepted",
        ai_generated=True,
        scheduled_date=_days_ago(-10)[:10],
        completed_date=None,
        created_at=_days_ago(14),
        sent_at=_days_ago(14),
        responded_at=_days_ago(12),
    ),
    CrmQuoteOut(
        id="quote-002",
        lead_id="lead-003",
        customer_name="Priya Nair",
        title="Storm Damage Roof Repair — Estimate",
        line_items=[
            QuoteLineItem(description="Shingle replacement — 12 squares", quantity=12, unit_price=340),
            QuoteLineItem(description="Flashing repair", quantity=1, unit_price=870),
        ],
        amount=4950,
        status="sent",
        ai_generated=True,
        created_at=_days_ago(3),
        sent_at=_days_ago(3),
    ),
    CrmQuoteOut(
        id="quote-003",
        lead_id=None,
        customer_name="Nathan Cole",
        title="Chimney Flashing Repair",
        line_items=[
            QuoteLineItem(description="Flashing materials + labor", quantity=1, unit_price=1200),
        ],
        amount=1200,
        status="accepted",
        ai_generated=False,
        scheduled_date=_days_ago(20)[:10],
        completed_date=_days_ago(18)[:10],
        created_at=_days_ago(22),
        sent_at=_days_ago(22),
        responded_at=_days_ago(21),
    ),
    CrmQuoteOut(
        id="quote-004",
        lead_id=None,
        customer_name="Nathan Cole",
        title="Spring Gutter Cleaning",
        line_items=[
            QuoteLineItem(description="Gutter cleaning — full perimeter", quantity=1, unit_price=280),
        ],
        amount=280,
        status="accepted",
        ai_generated=False,
        scheduled_date=_days_ago(-5)[:10],
        completed_date=None,
        created_at=_days_ago(4),
        sent_at=_days_ago(4),
        responded_at=_days_ago(3),
    ),
]

MOCK_INVOICES: list[InvoiceOut] = [
    InvoiceOut(
        id="invoice-001",
        quote_id="quote-003",
        customer_name="Nathan Cole",
        amount=1200,
        status="paid",
        due_date=_days_ago(25)[:10],
        paid_at=_days_ago(5),
        created_at=_days_ago(20),
    ),
    InvoiceOut(
        id="invoice-002",
        quote_id="quote-001",
        customer_name="Sarah Mitchell",
        amount=3840,
        status="sent",
        due_date=_days_ago(-15)[:10],
        paid_at=None,
        created_at=_days_ago(1),
    ),
    InvoiceOut(
        id="invoice-003",
        quote_id="quote-004",
        customer_name="Nathan Cole",
        amount=280,
        status="draft",
        due_date=None,
        paid_at=None,
        created_at=_hours_ago(2),
    ),
]

MOCK_CRM_DOCUMENTS: list[CrmDocumentOut] = [
    CrmDocumentOut(
        id="crmdoc-001",
        category="insurance",
        title="General Liability Insurance",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(300),
        tags=["compliance"],
        issuer="Texas Farm Bureau Insurance",
        expires_at=_days_ago(-20),
    ),
    CrmDocumentOut(
        id="crmdoc-002",
        category="license",
        title="TX Residential Roofing Contractor License",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(500),
        tags=["compliance"],
        issuer="Texas Department of Licensing and Regulation",
        expires_at=_days_ago(-200),
    ),
    CrmDocumentOut(
        id="crmdoc-003",
        category="contract",
        title="Signed Work Agreement — Gutter Guard Installation",
        file_url=None,
        file_type="pdf",
        uploaded_at=_days_ago(13),
        tags=["signed"],
        linked_customer="Sarah Mitchell",
        linked_quote_id="quote-001",
    ),
    CrmDocumentOut(
        id="crmdoc-004",
        category="photo",
        title="Chimney Flashing — Before Repair",
        file_url=None,
        file_type="jpg",
        uploaded_at=_days_ago(22),
        tags=["job-site"],
        linked_customer="Nathan Cole",
        linked_quote_id="quote-003",
    ),
]
