/**
 * API endpoint map — paths must match the FastAPI routers under
 * backend/app/api/v1 (see docs/architecture/03-api-architecture.md).
 */

export const ENDPOINTS = {
  me: "/users/me",
  dashboardHomeowner: "/dashboard/homeowner",
  projects: "/projects",
  project: (id: string) => `/projects/${id}`,
  projectQuotes: (id: string) => `/projects/${id}/quotes`,
  quotes: "/quotes",
  providers: "/providers",
  providersRecommended: "/providers/recommended",
  notifications: "/notifications",
  notificationRead: (id: string) => `/notifications/${id}/read`,
  documents: "/documents",
  document: (id: string) => `/documents/${id}`,
  serviceRecords: "/service-records",
  crmDashboard: "/crm/dashboard",
  crmCustomers: "/crm/customers",
  crmLeads: "/crm/leads",
  crmLeadAccept: (id: string) => `/crm/leads/${id}/accept`,
  crmLeadDecline: (id: string) => `/crm/leads/${id}/decline`,
  crmQuotes: "/crm/quotes",
  crmQuoteAiDraft: "/crm/quotes/ai-draft",
  crmOrders: "/crm/orders",
  crmInvoices: "/crm/invoices",
  crmInvoiceMarkPaid: (id: string) => `/crm/invoices/${id}/mark-paid`,
  crmDocuments: "/crm/documents",
  brandOverview: "/brand/overview",
  brandProducts: "/brand/products",
  brandProjects: "/brand/projects",
  brandDownloads: "/brand/downloads",
  brandDealers: "/brand/dealers",
  brandFaqs: "/brand/faqs",
  brandTickets: "/brand/tickets",
  brandTicketResolve: (id: string) => `/brand/tickets/${id}/resolve`,
  brandDashboard: "/brand/dashboard",
} as const;
